# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Splashscreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(798, 592)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dropShadowFrame = QtWidgets.QFrame(self.centralwidget)
        self.dropShadowFrame.setStyleSheet("QFrame{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.517, x2:1, y2:0.5, stop:0 rgba(255, 238, 252, 255), stop:0.9375 rgba(255, 101, 183, 255));\n"
"    color: rgb(255, 248, 254);\n"
"border-radius: 10px;\n"
"}")
        self.dropShadowFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dropShadowFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dropShadowFrame.setObjectName("dropShadowFrame")
        self.progressBar = QtWidgets.QProgressBar(self.dropShadowFrame)
        self.progressBar.setGeometry(QtCore.QRect(40, 400, 721, 41))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        self.progressBar.setFont(font)
        self.progressBar.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.progressBar.setMouseTracking(False)
        self.progressBar.setStyleSheet("QProgressBar{\n"
"    border-style:none;\n"
"    border-radius:20px;\n"
"    text-align:centre;\n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"\n"
"    \n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.517, x2:1, y2:0.5, stop:0 rgba(0, 45, 144, 255), stop:0.9375 rgba(85, 255, 255, 255));\n"
"    border-radius:20px;    \n"
"    color: rgb(202, 203, 255);\n"
"}")
        self.progressBar.setProperty("value", 30)
        self.progressBar.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignJustify)
        self.progressBar.setTextVisible(True)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.labeltitle = QtWidgets.QLabel(self.dropShadowFrame)
        self.labeltitle.setGeometry(QtCore.QRect(-4, 82, 781, 141))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.labeltitle.setFont(font)
        self.labeltitle.setStyleSheet("color: rgb(0, 58, 184);")
        self.labeltitle.setAlignment(QtCore.Qt.AlignCenter)
        self.labeltitle.setObjectName("labeltitle")
        self.labelarya = QtWidgets.QLabel(self.dropShadowFrame)
        self.labelarya.setGeometry(QtCore.QRect(-10, 180, 791, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.labelarya.setFont(font)
        self.labelarya.setStyleSheet("color: rgb(0, 45, 144);")
        self.labelarya.setAlignment(QtCore.Qt.AlignCenter)
        self.labelarya.setObjectName("labelarya")
        self.labelloading = QtWidgets.QLabel(self.dropShadowFrame)
        self.labelloading.setGeometry(QtCore.QRect(0, 450, 791, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelloading.setFont(font)
        self.labelloading.setStyleSheet("color: rgb(0, 45, 144);")
        self.labelloading.setAlignment(QtCore.Qt.AlignCenter)
        self.labelloading.setObjectName("labelloading")
        self.labelcreator = QtWidgets.QLabel(self.dropShadowFrame)
        self.labelcreator.setGeometry(QtCore.QRect(550, 520, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelcreator.setFont(font)
        self.labelcreator.setStyleSheet("background-color: rgb(255, 108, 187);\n"
"color: rgb(0, 45, 144);")
        self.labelcreator.setAlignment(QtCore.Qt.AlignCenter)
        self.labelcreator.setObjectName("labelcreator")
        self.verticalLayout.addWidget(self.dropShadowFrame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AI assistant"))
        self.labeltitle.setText(_translate("MainWindow", "<Strong>AI</Strong> Assistant"))
        self.labelarya.setText(_translate("MainWindow", "<Strong>ARYA"))
        self.labelloading.setText(_translate("MainWindow", "Loading..."))
        self.labelcreator.setText(_translate("MainWindow", "<Strong>Created by:</Strong> KEC BCT 73"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
