# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Starting.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Starting(object):
    def setupUi(self, Starting):
        Starting.setObjectName("Starting")
        Starting.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Starting)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QFrame{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.0909091 rgba(158, 151, 255, 255), stop:0.965909 rgba(217, 201, 255, 255));\n"
"    \n"
"    color: rgb(254, 242, 255);\n"
"    border-radius: 10px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(270, 490, 211, 71))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(27)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("\n"
"    border-radius: 10px;\n"
"        background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.0909091 rgba(255, 202, 255, 255), stop:0.965909 rgba(255, 229, 248, 255));\n"
"    \n"
"color: rgb(85, 85, 255);\n"
"border-color: rgb(222, 188, 255);\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.close = QtWidgets.QPushButton(self.frame)
        self.close.setGeometry(QtCore.QRect(740, 0, 41, 41))
        self.close.setStyleSheet("background-color: rgb(217, 201, 255);\n"
"border-radius: 10px;")
        self.close.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui/chatbot assests/1200px-Flat_cross_icon.svg.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close.setIcon(icon)
        self.close.setIconSize(QtCore.QSize(32, 32))
        self.close.setObjectName("close")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(550, 100, 211, 351))
        self.frame_2.setStyleSheet("QFrame{\n"
"\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.0909091 rgba(255, 202, 255, 255), stop:0.965909 rgba(255, 229, 248, 255));\n"
"border: 5px;\n"
"    border-color: rgb(255, 139, 110);\n"
"border-radius: 20px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(10, 10, 191, 331))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(85, 85, 255);")
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(10, 30, 211, 171))
        self.frame_3.setStyleSheet("QFrame{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.0909091 rgba(255, 202, 255, 255), stop:0.965909 rgba(255, 229, 248, 255));\n"
"border-radius: 20px;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setGeometry(QtCore.QRect(20, -30, 171, 221))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(85, 85, 255);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.frame)
        Starting.setCentralWidget(self.centralwidget)

        self.retranslateUi(Starting)
        QtCore.QMetaObject.connectSlotsByName(Starting)

    def retranslateUi(self, Starting):
        _translate = QtCore.QCoreApplication.translate
        Starting.setWindowTitle(_translate("Starting", "MainWindow"))
        self.pushButton.setText(_translate("Starting", "Start Up"))
        self.label.setText(_translate("Starting", "<html><head/><body><p><span style=\" font-weight:600;\">This is Arya.</span></p><p><span style=\" font-weight:600;\">She is an Artificial Intelligence</span></p><p><span style=\" font-weight:600;\">Assistant.She can perform a </span></p><p><span style=\" font-weight:600;\">lot of tasks and have</span></p><p><span style=\" font-weight:600;\">small coversations with you.</span></p><p><span style=\" font-weight:600;\"><br/></span></p><p><span style=\" font-weight:600;\">She was created using NLP </span></p><p><span style=\" font-weight:600;\">using Python\'s Torch. She is</span></p><p><span style=\" font-weight:600;\">always evolving and learning.</span></p><p><br/></p><p><span style=\" font-weight:600;\">Press the Button to wake her</span></p><p><span style=\" font-weight:600;\">up!</span></p></body></html>"))
        self.label_2.setText(_translate("Starting", "<html><head/><body><p><span style=\" font-weight:600; font-style:italic;\">Created by:</span></p><p><span style=\" font-weight:600; font-style:italic;\">Aaryan Poudel</span></p><p><span style=\" font-weight:600; font-style:italic;\">Abishkar Jung Shah</span></p><p><span style=\" font-weight:600; font-style:italic;\">Basanta Niraula</span></p><p><span style=\" font-weight:600; font-style:italic;\">Kiyas Piya</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Starting = QtWidgets.QMainWindow()
    ui = Ui_Starting()
    ui.setupUi(Starting)
    Starting.show()
    sys.exit(app.exec_())
