# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Working.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Working(object):
    def setupUi(self, Working):
        Working.setObjectName("Working")
        Working.resize(1344, 896)
        self.centralwidget = QtWidgets.QWidget(Working)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.baseframe = QtWidgets.QFrame(self.centralwidget)
        self.baseframe.setStyleSheet("QFrame{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.0909091 rgba(255, 202, 255, 255), stop:0.965909 rgba(255, 229, 248, 255));\n"
"color:rgb(255, 243, 255);\n"
"border-radius:10px;\n"
"}")
        self.baseframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.baseframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.baseframe.setObjectName("baseframe")
        self.frame = QtWidgets.QFrame(self.baseframe)
        self.frame.setGeometry(QtCore.QRect(10, 560, 1301, 301))
        self.frame.setStyleSheet("QFrame{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.0909091 rgba(241, 255, 147, 255), stop:0.948864 rgba(254, 255, 244, 255));\n"
"    color: rgb(255, 255, 255);\n"
"border-radius: 20px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.user = QtWidgets.QLabel(self.frame)
        self.user.setGeometry(QtCore.QRect(20, 30, 1251, 111))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(15)
        self.user.setFont(font)
        self.user.setStyleSheet("color: rgb(0, 0, 0);")
        self.user.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.user.setObjectName("user")
        self.arya = QtWidgets.QLabel(self.frame)
        self.arya.setGeometry(QtCore.QRect(20, 170, 1251, 111))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(15)
        self.arya.setFont(font)
        self.arya.setStyleSheet("color: rgb(0, 0, 0);")
        self.arya.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.arya.setObjectName("arya")
        self.arya.setWordWrap(True)
        self.scrollArea = QtWidgets.QScrollArea(self.frame)
        self.scrollArea.setGeometry(QtCore.QRect(9, 159, 1281, 131))
        self.scrollArea.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.0909091 rgba(241, 255, 147, 255), stop:0.948864 rgba(254, 255, 244, 255));")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 1281, 131))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_5)
        self.scrollArea.raise_()
        self.user.raise_()
        self.arya.raise_()
        self.close = QtWidgets.QPushButton(self.baseframe)
        self.close.setGeometry(QtCore.QRect(1280, 0, 41, 41))
        self.close.setStyleSheet("background-color: rgb(255, 229, 248);\n"
"border-radius: 10px;")
        self.close.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui/chatbot assests/1200px-Flat_cross_icon.svg.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close.setIcon(icon)
        self.close.setIconSize(QtCore.QSize(32, 32))
        self.close.setObjectName("close")
        self.frame_2 = QtWidgets.QFrame(self.baseframe)
        self.frame_2.setGeometry(QtCore.QRect(19, 19, 271, 521))
        self.frame_2.setStyleSheet("QFrame{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:20px;\n"
"}\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(20, 20, 231, 481))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(0, 0, 0);")
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.baseframe)
        Working.setCentralWidget(self.centralwidget)

        self.retranslateUi(Working)
        QtCore.QMetaObject.connectSlotsByName(Working)

    def retranslateUi(self, Working):
        _translate = QtCore.QCoreApplication.translate
        Working.setWindowTitle(_translate("Working", "MainWindow"))
        self.user.setText(_translate("Working", "User asks..."))
        self.arya.setText(_translate("Working", "<html><head/><body><p>Arya says...</p></body></html>"))
        self.label.setText(_translate("Working", "<html><head/><body><p>Some of the quick commands:</p><p>1. Tell me the time.</p><p>2. Tell me the date.</p><p>3. Open Youtube.</p><p>4. Open my webbrowser.</p><p>5. Open Facebook</p><p>6. Send an email.</p><p>7. Tell me a joke.</p><p>8. Check the weather.</p><p>9. Predict rain.</p><p>10. Play a song.</p><p>11. Make a Google Search.</p><p>12. Open Calculator.</p></body></html>"))

    def update_user(self,str):
        self.user.setText(str)

    def update_arya(self,str1):
        self.arya.setText(str1)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Working = QtWidgets.QMainWindow()
    ui = Ui_Working()
    ui.setupUi(Working)
    Working.show()
    sys.exit(app.exec_())
